eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:50101/eureka/
server:
  port: 31200
spring:
  application:
    name: xc_service_mange_course
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 10000
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
pagehelper:
  helper-dialect: mysql
mybatis:
  type-aliases-package: com.czxy.xuecheng.domain.course
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
course-publish:
  siteId: 5b30cba5f58b4411fc6cb1e5
  templateId: 5f223feb8503ae52c894eea7
  dataUrlPre: http://localhost:31200/course/courseview/
  pagePhysicalPath: /course/detail/
  pageWebPath: /course/detail/
  previewUrl: http://www.xuecheng.com/cms/preview/
